### ISSUE TITLE
Fatal Error caused by This mod

### ISSUE THREAD

**Issue by Caldeiradas** [sudolev/DynamicVillageMod#9] opened 2023-12-28 18:53 UTC
Good day!  
I was having a problem in my Single Player World and that mod was the cause (I tried to replicate the error turning off one mod at the time)  
Further more, loading the area without the mod, re-add the mod and then go to the area where the error will not trigger any error.

Here is the crash report:  
[crash-2023-12-21_14.30.41-server.txt](https://github.com/sudolev/DynamicVillageMod/files/13788700/crash-2023-12-21_14.30.41-server.txt)

I hope the error get's fixed as I was using the mod for first time and I was really enjoying!

Pack: [Creation Engineering.zip](https://github.com/sudolev/DynamicVillageMod/files/13788728/Creation.Engineering.zip)  
Seed: 5237505980291335206  
Coordinates: [293 117 -1621] [X Y Z]  
> /tp 293 117 -1621

Thank you for your time and attention!

**Comment by sudolev** [comment] 2023-12-28 19:18
Sorry, I'm not really working on this mod any more. Never really left a testing/early beta stage. This error is caused by something broken in the structure file for one of the structures and is a duplicate of #6.
I apologize, but your best course of action is probably to remove the mod. Sorry. Thank you for the issue.

**Closed by sudolev** 2023-12-28 19:18 UTC

**Comment by Caldeiradas** [comment] 2023-12-28 19:29
Please! Come back to it! It is fun and interesting!  
I even have some ideas for you.

If you can, come back to it.  

Ps.: My name in Discord is Half_676767.  
Thank you!
